// Generated by nuxi
/// <reference types="@primevue/nuxt-module" />
<<<<<<< HEAD
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxt/telemetry" />
=======
>>>>>>> 52640c3214e27cb5914a7625baac8b5a98be0d45
/// <reference types="@nuxt/devtools" />
/// <reference types="nuxt" />
/// <reference path="types/app-defaults.d.ts" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/build.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference types="@pinia/nuxt" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
