// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/7/2024, 14:57:07
const configMerger = require("C:/Users/simba/OneDrive/Desktop/okproject/ok/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/simba/OneDrive/Desktop/okproject/ok/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/plugins/**/*.{js,ts,mjs}","C:/Users/simba/OneDrive/Desktop/okproject/ok/composables/**/*.{js,ts,mjs}","C:/Users/simba/OneDrive/Desktop/okproject/ok/utils/**/*.{js,ts,mjs}","C:/Users/simba/OneDrive/Desktop/okproject/ok/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/simba/OneDrive/Desktop/okproject/ok/app.config.{js,ts,mjs}"] }));

module.exports = config
